// SPDX-License-Identifier: GPL-3.0

pragma solidity ^0.8.17;

error AlreadyInitialized();
error AlreadyAdded();
error AmountExceedsBalance();
error DecreasedAllowanceBelowZero();
error DepositMoreThanMax();
error IncompatibleLengths();
error IncompatibleTokens();
error IncompatibleValues();
error Initializing();
error InsufficientAllowance();
error InvalidParam();
error InvalidParams();
error InvalidTokens();
error InvalidToAddress();
error InvalidSwap();
error MintMoreThanMax();
error NoRightsOnToken();
error NotCollateral();
error NotGovernor();
error NotGovernorOrGuardian();
error NotInitializing();
error NotModule();
error NotTrusted();
error OneInchSwapFailed();
error Paused();
error RedeemMoreThanMax();
error SupportedTokensNotRemoved();
error TokenDebtNotRepaid();
error TooBigAmountIn();
error TooSmallAmountOut();
error TooLate();
error Whitelisted();
error WithdrawFeeTooLarge();
error WithdrawMoreThanMax();
error ZeroAddress();
error ZeroAddressFrom();
error ZeroAddressTo();
